### ISSUE TITLE
No funca

### ISSUE THREAD

**Issue by mdb1** [jnvillar/hackaton-galicia-2017#1]
Todo este repo no funca sin la apikey

https://github.com/jnvillar/hackaton-galicia-2017/blob/dfffd68569529110eb8a3b4bcebafab9025bda4e/src/main/groovy/buy/BuyType.groovy#L8

**Comment by jnvillar** [comment]
La apiKey fue borrada aproposito para que nadie tenga acceso a las apis de galicia
